### ISSUE TITLE
Impossible d'installer le greffon t411 dans qBittorent v3.1.9.2

### ISSUE THREAD

**Issue by Twanislas** [davy39/qbfrench#1]
Bonjour !

Je ne parviens pas à installer le greffon t411.py. J'ai bien modifié le fichier et installé python ;)
L'erreur que j'obtiens est "Le greffon de recherche n'a pas pu être installé".

Merci pour toute aide éventuelle ;)

Antoine /

**Comment by prabelalexis** [comment]
Bonjour, 

je peux lancer que un torrent par un torrent t411. vous avez une idée ?
