### ISSUE TITLE
Update Cpasbien and Smartorrent plugins

### ISSUE THREAD

**Issue by ngosang** [davy39/qbfrench#3]
@davy39 the Cpasbien and Smartorrent plugins are outdated. Could you fix it?

 These plugins are compatible with Python2 and Python3, you can see how they work:
* https://raw.githubusercontent.com/MrNeon/qbittorrent-search-plugins/master/strikesearch.py
* https://raw.githubusercontent.com/ngosang/qBittorrent-plugins/master/tntvillage.py

After any changes update:
https://github.com/qbittorrent/qBittorrent/wiki/Unofficial-search-plugins

**Comment by Pireo** [comment]
I've added omg torrent again, on python3 it doesn't install

**Comment by simonbru** [comment]
I did a pull request that should fix this issue #4

**Comment by davy39** [comment]
Sorry for not answering to this issue, I've just seen it years after... I did merge simonbru's pull request. Thanks for his work
